routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

////////////
// AUTHOR //
////////////
Route::namespace('Author')
    ->name('author.')
    ->middleware(['auth', 'auth.author'])
    ->group(function() {
        Route::get('/admin', 'AuthorController@index')
            ->name('index');
        Route::post('/admin/store', 'AuthorController@store')
            ->name('author.store');
        Route::get('/admin/admin_list', 'AuthorController@admin')
            ->name('user');
        Route::get('/admin/{id}/edit', 'AuthorController@edit');
        Route::get('/admin/mentor', 'AuthorController@mentor')
            ->name('mentor');
        Route::post('/mentor/add', 'AuthorController@addMentor')
            ->name('addMentor');
        Route::get('/mentor/{id}/edit', 'AuthorController@editMentor');
        Route::post('/mentor/update', 'AuthorController@updateMentor')
            ->name('updateMentor');
        Route::post('/mentor/delete/{id}', 'AuthorController@deleteMentor');
});


////////////////
// 01 ASAHAN //
///////////////
Route::namespace('AdminAsahan')
    ->name('asahan.')
    ->middleware(['auth', 'auth.asahan'])
    ->group(function() {
        Route::get('/asahan', 'AdminController@index')
            ->name('dashboard');
        Route::get('/asahan/all', 'AdminController@all')
            ->name('all');
        Route::get('/asahan/{id}/edit', 'AdminController@edit');
        Route::post('/asahan/add', 'AdminController@add')
            ->name('add');
        Route::post('/asahan/update', 'AdminController@update')
            ->name('update');
        Route::post('/asahan/destroy/{id}', 'AdminController@destroy');
        Route::post('/asahan/cancel/{id}/lt1', 'AdminController@cancelLt1');
        Route::post('/asahan/cancel/{id}/lt2', 'AdminController@cancelLt2');
        Route::post('/asahan/cancel/{id}/lt3', 'AdminController@cancelLt3');

        // LT 1, LT 2, LT 3
        Route::get('/asahan/lt1', 'AdminController@lt1')
            ->name('ltsatu');
        Route::get('/asahan/lt2', 'AdminController@lt2')
            ->name('ltdua');
        Route::get('/asahan/lt3', 'AdminController@lt3')
            ->name('lttiga');
        Route::get('/asahan/{id}/lt1', 'AdminController@ltsatu');
        Route::get('/asahan/{id}/lt2', 'AdminController@ltdua');
        Route::get('/asahan/{id}/lt3', 'AdminController@lttiga');
        Route::post('/asahan/tambah/lt1', 'AdminController@ltsatuTambah')
            ->name('ltsatuTambah');
        Route::post('/asahan/tambah/lt2', 'AdminController@ltduaTambah')
            ->name('ltduaTambah');
        Route::post('/asahan/tambah/lt3', 'AdminController@lttigaTambah')
            ->name('lttigaTambah');

        // Export into Excel, PDF
        Route::get('/asahan/excel', 'AdminController@excel')
            ->name('excel');

        // PDF Generate
        Route::get('/asahan/pdf', 'AdminController@pdfgenerate')
            ->name('pdf');
        Route::get('/asahan/print', 'AdminController@pdfprint')
            ->name('print');
        Route::get('/asahan/card/{id}', 'AdminController@card')
            ->name('card');
        Route::get('/asahan/setting', 'AdminController@setting')
            ->name('setting');
        Route::post('/asahan/setting/update', 'AdminController@changePass');
});


//////////////////
// 02 BATU BARA //
//////////////////
Route::namespace('AdminBatubara')
    ->name('batubara.')
    ->middleware(['auth', 'auth.batubara'])
    ->group(function() {
        Route::get('/batubara', 'AdminController@index')
            ->name('dashboard');
        Route::get('/batubara/all', 'AdminController@all')
            ->name('all');
        Route::get('/batubara/{id}/edit', 'AdminController@edit');
        Route::post('/batubara/add', 'AdminController@add')
            ->name('add');
        Route::post('/batubara/update', 'AdminController@update')
            ->name('update');
        Route::post('/batubara/destroy/{id}', 'AdminController@destroy');
        Route::post('/batubara/cancel/{id}/lt1', 'AdminController@cancelLt1');
        Route::post('/batubara/cancel/{id}/lt2', 'AdminController@cancelLt2');
        Route::post('/batubara/cancel/{id}/lt3', 'AdminController@cancelLt3');

        // LT 1, LT 2, LT 3
        Route::get('/batubara/lt1', 'AdminController@lt1')
            ->name('ltsatu');
        Route::get('/batubara/lt2', 'AdminController@lt2')
            ->name('ltdua');
        Route::get('/batubara/lt3', 'AdminController@lt3')
            ->name('lttiga');
        Route::get('/batubara/{id}/lt1', 'AdminController@ltsatu');
        Route::get('/batubara/{id}/lt2', 'AdminController@ltdua');
        Route::get('/batubara/{id}/lt3', 'AdminController@lttiga');
        Route::post('/batubara/tambah/lt1', 'AdminController@ltsatuTambah')
            ->name('ltsatuTambah');
        Route::post('/batubara/tambah/lt2', 'AdminController@ltduaTambah')
            ->name('ltduaTambah');
        Route::post('/batubara/tambah/lt3', 'AdminController@lttigaTambah')
            ->name('lttigaTambah');

        // Export into Excel, PDF
        Route::get('/batubara/excel', 'AdminController@excel')
            ->name('excel');

        // PDF Generate
        Route::get('/batubara/pdf', 'AdminController@pdfgenerate')
            ->name('pdf');
        Route::get('/batubara/print', 'AdminController@pdfprint')
            ->name('print');
        Route::get('/batubara/card/{id}', 'AdminController@card')
            ->name('card');
        Route::get('/batubara/setting', 'AdminController@setting')
            ->name('setting');
        Route::post('/batubara/setting/update', 'AdminController@changePass');
});


//////////////
// 03 DAIRI //
//////////////
Route::namespace('AdminDairi')
    ->name('dairi.')
    ->middleware(['auth', 'auth.dairi'])
    ->group(function() {
        Route::get('/dairi', 'AdminController@index')
            ->name('dashboard');
        Route::get('/dairi/all', 'AdminController@all')
            ->name('all');
        Route::get('/dairi/{id}/edit', 'AdminController@edit');
        Route::post('/dairi/add', 'AdminController@add')
            ->name('add');
        Route::post('/dairi/update', 'AdminController@update')
            ->name('update');
        Route::post('/dairi/destroy/{id}', 'AdminController@destroy');
        Route::post('/dairi/cancel/{id}/lt1', 'AdminController@cancelLt1');
        Route::post('/dairi/cancel/{id}/lt2', 'AdminController@cancelLt2');
        Route::post('/dairi/cancel/{id}/lt3', 'AdminController@cancelLt3');

        // LT 1, LT 2, LT 3
        Route::get('/dairi/lt1', 'AdminController@lt1')
            ->name('ltsatu');
        Route::get('/dairi/lt2', 'AdminController@lt2')
            ->name('ltdua');
        Route::get('/dairi/lt3', 'AdminController@lt3')
            ->name('lttiga');
        Route::get('/dairi/{id}/lt1', 'AdminController@ltsatu');
        Route::get('/dairi/{id}/lt2', 'AdminController@ltdua');
        Route::get('/dairi/{id}/lt3', 'AdminController@lttiga');
        Route::post('/dairi/tambah/lt1', 'AdminController@ltsatuTambah')
            ->name('ltsatuTambah');
        Route::post('/dairi/tambah/lt2', 'AdminController@ltduaTambah')
            ->name('ltduaTambah');
        Route::post('/dairi/tambah/lt3', 'AdminController@lttigaTambah')
            ->name('lttigaTambah');

        // Export into Excel, PDF
        Route::get('/dairi/excel', 'AdminController@excel')
            ->name('excel');

        // PDF Generate
        Route::get('/dairi/pdf', 'AdminController@pdfgenerate')
            ->name('pdf');
        Route::get('/dairi/print', 'AdminController@pdfprint')
            ->name('print');
        Route::get('/dairi/card/{id}', 'AdminController@card')
            ->name('card');
        Route::get('/dairi/setting', 'AdminController@setting')
            ->name('setting');
        Route::post('/dairi/setting/update', 'AdminController@changePass');
});


/////////////////////
// 04 DELI SERDANG //
/////////////////////
Route::namespace('AdminDeliserdang')
    ->name('deliserdang.')
    ->middleware(['auth', 'auth.deliserdang'])
    ->group(function() {
        Route::get('/deliserdang', 'AdminController@index')
            ->name('dashboard');
        Route::get('/deliserdang/all', 'AdminController@all')
            ->name('all');
        Route::get('/deliserdang/{id}/edit', 'AdminController@edit');
        Route::post('/deliserdang/add', 'AdminController@add')
            ->name('add');
        Route::post('/deliserdang/update', 'AdminController@update')
            ->name('update');
        Route::post('/deliserdang/destroy/{id}', 'AdminController@destroy');
        Route::post('/deliserdang/cancel/{id}/lt1', 'AdminController@cancelLt1');
        Route::post('/deliserdang/cancel/{id}/lt2', 'AdminController@cancelLt2');
        Route::post('/deliserdang/cancel/{id}/lt3', 'AdminController@cancelLt3');

        // LT 1, LT 2, LT 3
        Route::get('/deliserdang/lt1', 'AdminController@lt1')
            ->name('ltsatu');
        Route::get('/deliserdang/lt2', 'AdminController@lt2')
            ->name('ltdua');
        Route::get('/deliserdang/lt3', 'AdminController@lt3')
            ->name('lttiga');
        Route::get('/deliserdang/{id}/lt1', 'AdminController@ltsatu');
        Route::get('/deliserdang/{id}/lt2', 'AdminController@ltdua');
        Route::get('/deliserdang/{id}/lt3', 'AdminController@lttiga');
        Route::post('/deliserdang/tambah/lt1', 'AdminController@ltsatuTambah')
            ->name('ltsatuTambah');
        Route::post('/deliserdang/tambah/lt2', 'AdminController@ltduaTambah')
            ->name('ltduaTambah');
        Route::post('/deliserdang/tambah/lt3', 'AdminController@lttigaTambah')
            ->name('lttigaTambah');

        // Export into Excel, PDF

app/Models/Asahan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Asahan extends Model
{
    protected $guarded = [];
}

resources/views/admin/asahan/_lt1.blade.php
@extends('layouts.master')
@section('title')
LT 1 | {{ Auth::user()->username }}
@endsection

@section('content')
<div class="card-box table-responsive">
    <div class="btn-group" role="group" aria-label="Basic example">
      <a href="{{ route('asahan.all') }}" class="btn btn-light">Semua Data</a>
      <a href="{{ route('asahan.ltsatu') }}" class="btn btn-primary">LT 1</a>
      <a href="{{ route('asahan.ltdua') }}" class="btn btn-light">LT 2</a>
      <a href="{{ route('asahan.lttiga') }}" class="btn btn-light">LT 3</a>
    </div>
<hr>
    
    <br>
    <h4 class="header-title">Data Anggota LT 1</h4>

    <table id="datatable" class="table table-bordered  dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
        <thead class="bg-primary text-light">
            <tr>
                <th class="text-center">#</th>
                <th class="text-center">No. Anggota</th>
                <th class="text-center">Nama Lengkap</th>
                <th class="text-center">JK</th>
                <th class="text-center">Tgl. Lahir</th>
                <th class="text-center">LT 1</th>
                <th class="text-center">Create by</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        <tbody class="text-center">
        @foreach($member as $key => $row)
            <tr>
               <td>{{ ++$key }}</td>
               <td>{{ $row->no_anggota }}</td>
               <td>{{ $row->nama }}</td>
               <td>{{ $row->jenis_kelamin }}</td>
               <td>{{ $row->tanggal_lahir }}</td>
               <td><i class="fa fa-check text-success"></i> {{ $row->lead_train_satu }}</td>
               <td>{{ $row->created_by }}</td>
               <td>
                  <a href="#" class="ltsatu btn btn-sm btn-info" id="{{ $row->id }}"><i class="fa fa-edit"></i> Edit</a>
                  <a href="#" class="cancel btn btn-sm btn-warning" onclick="cancelConfirmation({{ $row->id }});"><i class="fa fa-times"></i> Batal</a>
               </td>
            </tr>
         @endforeach
        </tbody>
    </table>
</div>

<!-- Modals -->
@include('partials.modals._lt1')

<script>
$(document).ready(function() {
  
    // Datepicker Add LT 1
    $('.datepickerssss').datepicker({ uiLibrary: 'bootstrap', format: 'dd mmmm yyyy' });
    $(document).on('click', '.ltsatu', function() {
      var id = $(this).attr('id');
      $('#form_results').html('');
      $.ajax({
        url: '/asahan/'+id+'/lt1',
        dataType: 'json',
        success: function(data) {
          $('#formModals').modal('show');
          $('#action_buttons').val('Update LT 1');
          $('#actions').val('Update');
          $('#lead_train_satus').val(data.data.lead_train_satu);
          $('#hidden_ids').val(data.data.id);
        }
      });
    });

    $('#sample_forms').on('submit', function(event) {
      event.preventDefault();
      var id = $(this).attr('id');

      $.ajax({
        url: "{{ route('asahan.ltsatuTambah') }}",
        method: 'POST',
        data: $(this).serialize(),
        dataType: 'json',
        success: function(data) {
          var html = '';
          if (data.errors) {
            html = '<div class="alert alert-danger">';
            for (var count = 0; count < data.errors.length; count++) {
                html += '<li><b>'+data.errors[count]+'</b></li>';
            }
            html += '</div>';
          }

          if (data.success) {
            Swal.fire({
              type: 'success',
              icon: 'success',
              title: 'Berhasil',
              text: 'Data LT 1 berhasil ditambah'
            }).then(function() {
              location.reload();
            });
            $('#formModals').modal('hide');
            // html = '<div class="alert alert-success">'+data.success+'</div>';
            $('#sample_forms')[0].reset();
          }
          $('#form_results').html(html);
        }
      });
    });
  }); 
  
  function cancelConfirmation(id) {
    Swal.fire({
      icon: 'warning',
      title: "Batalkan?",
      text: "Apakah anda yakin ingin membatalkan Lead Train 2?",
      type: "warning",
      showCancelButton: !0,
      confirmButtonText: "Yes, Batalkan!",
      cancelButtonText: "Tidak!",
      reverseButtons: !0
    }).then(function (event) {
      if (event.value === true) {
        var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');

        $.ajax({
          type: 'POST',
          url: '/asahan/cancel/'+id+'/lt1',
          data: { _token: CSRF_TOKEN },
          dataType: 'JSON',
          success: function (results) {
            if (results.success === true) {
              Swal.fire({
                toast: false,
                icon: 'success',
                title: "Success",
                text: "Data Deleted",
                showConfirmButton: true,
                // timer: 1500
              }).then(function() {
                location.href = '{{ URL("/asahan/all") }}';
              });
            } else {
              Swal.fire("Error!", results.message, "error");
            }
          }
        });
      } else {
        e.dismiss;
      }
    }, function (dismiss) {
      return false;
    });
  }
</script>

@endsection

resources/views/admin/asahan/_lt2.blade.php
@extends('layouts.master')
@section('title')
LT 2 | {{ Auth::user()->username }}
@endsection

@section('content')
<div class="card-box table-responsive">
    <div class="btn-group" role="group" aria-label="Basic example">
      <a href="{{ route('asahan.all') }}" class="btn btn-light">Semua Data</a>
      <a href="{{ route('asahan.ltsatu') }}" class="btn btn-light">LT 1</a>
      <a href="{{ route('asahan.ltdua') }}" class="btn btn-primary">LT 2</a>
      <a href="{{ route('asahan.lttiga') }}" class="btn btn-light">LT 3</a>
    </div>
<hr>
    
    <br>
    <h4 class="header-title">Data Anggota LT 2</h4>

    <table id="datatable" class="table table-bordered  dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
        <thead class="bg-primary text-light">
            <tr>
                <th class="text-center">#</th>
                <th class="text-center">No. Anggota</th>
                <th class="text-center">Nama Lengkap</th>
                <th class="text-center">JK</th>
                <th class="text-center">Tgl. Lahir</th>
                <th class="text-center">LT 2</th>
                <th class="text-center">Create by</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        <tbody class="text-center">
        @foreach($member as $key => $row)
            <tr>
               <td>{{ ++$key }}</td>
               <td>{{ $row->no_anggota }}</td>
               <td>{{ $row->nama }}</td>
               <td>{{ $row->jenis_kelamin }}</td>
               <td>{{ $row->tanggal_lahir }}</td>
               <td><i class="fa fa-check text-success"></i> {{ $row->lead_train_dua }}</td>
               <td>{{ $row->created_by }}</td>
               <td>
                  <a href="#" class="ltdua btn btn-sm btn-info" id="{{ $row->id }}"><i class="fa fa-edit"></i> Edit</a>
                  <a href="#" class="cancel btn btn-sm btn-warning" onclick="cancelConfirmation({{ $row->id }});"><i class="fa fa-times"></i> Batal</a>
               </td>
            </tr>
         @endforeach
        </tbody>
    </table>
</div>

@include('partials.modals._lt2')

<script>
// LT 2
$(document).ready(function() {
    $('.datepickerss').datepicker({ uiLibrary: 'bootstrap', format: 'dd mmmm yyyy' });
$(document).on('click', '.ltdua', function() {
      var id = $(this).attr('id');
      $('#form_resultss').html('');
      $.ajax({
        url: '/asahan/'+id+'/lt2',
        dataType: 'json',
        success: function(data) {
          $('#formModalss').modal('show');
          $('#action_buttonss').val('Update LT 2');
          $('#actionss').val('Update');
          $('#lead_train_duass').val(data.data.lead_train_dua);
          $('#hidden_idss').val(data.data.id);
        }
      });
    });

    $('#sample_formss').on('submit', function(event) {
      event.preventDefault();
      var id = $(this).attr('id');

      $.ajax({
        url: "{{ route('asahan.ltduaTambah') }}",
        method: 'POST',
        data: $(this).serialize(),
        dataType: 'json',
        success: function(data) {
          var html = '';
          if (data.errors) {
            html = '<div class="alert alert-danger">';
            for (var count = 0; count < data.errors.length; count++) {
                html += '<li><b>'+data.errors[count]+'</b></li>';
            }
            html += '</div>';
          }

          if (data.success) {
            Swal.fire({
              type: 'success',
              icon: 'success',
              title: 'Berhasil',
              text: 'Data LT 2 berhasil ditambah'
            }).then(function() {
              location.reload();
            });
            $('#formModalss').modal('hide');
            // html = '<div class="alert alert-success">'+data.success+'</div>';
            $('#sample_formss')[0].reset();
          }
          $('#form_resultss').html(html);
        }
      });
    });
  });

  function cancelConfirmation(id) {
    Swal.fire({
      icon: 'warning',
      title: "Batalkan?",
      text: "Apakah anda yakin ingin membatalkan Lead Train 2?",
      type: "warning",
      showCancelButton: !0,
      confirmButtonText: "Yes, Batalkan!",
      cancelButtonText: "Tidak!",
      reverseButtons: !0
    }).then(function (event) {
      if (event.value === true) {
        var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');

        $.ajax({
          type: 'POST',
          url: '/asahan/cancel/'+id+'/lt2',
          data: { _token: CSRF_TOKEN },
          dataType: 'JSON',
          success: function (results) {
            if (results.success === true) {
              Swal.fire({
                toast: false,
                icon: 'success',
                title: "Success",
                text: "Data Deleted",
                showConfirmButton: true,
                // timer: 1500
              }).then(function() {
                location.href = '{{ URL("/asahan/lt1") }}';
              });
            } else {
              Swal.fire("Error!", results.message, "error");
            }
          }
        });
      } else {
        e.dismiss;
      }
    }, function (dismiss) {
      return false;
    });
  }
</script>

@endsection

resources/views/admin/asahan/_lt3.blade.php
@extends('layouts.master')
@section('title')
LT 3 | {{ Auth::user()->username }}
@endsection

@section('content')
<div class="card-box table-responsive">
    <div class="btn-group" role="group" aria-label="Basic example">
      <a href="{{ route('asahan.all') }}" class="btn btn-light">Semua Data</a>
      <a href="{{ route('asahan.ltsatu') }}" class="btn btn-light">LT 1</a>
      <a href="{{ route('asahan.ltdua') }}" class="btn btn-light">LT 2</a>
      <a href="{{ route('asahan.lttiga') }}" class="btn btn-primary">LT 3</a>
    </div>
<hr>
    
    <br>
    <h4 class="header-title">Data Anggota LT 3</h4>

    <table id="datatable" class="table table-bordered  dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
        <thead class="bg-primary text-light">
            <tr>
                <th class="text-center">#</th>
                <th class="text-center">No. Anggota</th>
                <th class="text-center">Nama Lengkap</th>
                <th class="text-center">JK</th>
                <th class="text-center">Tgl. Lahir</th>
                <th class="text-center">LT 3</th>
                <th class="text-center">Create by</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        <tbody class="text-center">
        @foreach($member as $key => $row)
            <tr>
               <td>{{ ++$key }}</td>
               <td>{{ $row->no_anggota }}</td>
               <td>{{ $row->nama }}</td>
               <td>{{ $row->jenis_kelamin }}</td>
               <td>{{ $row->tanggal_lahir }}</td>
               <td><i class="fa fa-check text-success"></i> {{ $row->lead_train_tiga }}</td>
               <td>{{ $row->created_by }}</td>
               <td>
                  <a href="#" class="ltiga btn btn-sm btn-info" id="{{ $row->id }}"><i class="fa fa-edit"></i> Edit</a>
                  <a href="#" class="cancel btn btn-sm btn-warning" onclick="cancelConfirmation({{ $row->id }});"><i class="fa fa-times"></i> Batal</a>
               </td>
            </tr>
         @endforeach
        </tbody>
    </table>
</div>

<!-- Modals -->
@include('partials.modals._lt3')

<script>
$(document).ready(function() {
  
    // Datepicker Add LT 3
    $('.datepickersss').datepicker({ uiLibrary: 'bootstrap', format: 'dd mmmm yyyy' });
   $(document).on('click', '.ltiga', function() {
      $('#formModalsss').modal('show');var id = $(this).attr('id');
      $('#form_resultsss').html('');
      $.ajax({
        url: '/asahan/'+id+'/lt3',
        dataType: 'json',
        success: function(data) {
          $('#formModalsss').modal('show');
          $('#action_buttonsss').val('Update LT 3');
          $('#actionsss').val('Update');
          $('#lead_train_tigasss').val(data.data.lead_train_tiga);
          $('#hidden_idsss').val(data.data.id);
        }
      });
    });

    $('#sample_formsss').on('submit', function(event) {
      event.preventDefault();
      var id = $(this).attr('id');

      $.ajax({
        url: "{{ route('asahan.lttigaTambah') }}",
        method: 'POST',
        data: $(this).serialize(),
        dataType: 'json',
        success: function(data) {
          var html = '';
          if (data.errors) {
            html = '<div class="alert alert-danger">';
            for (var count = 0; count < data.errors.length; count++) {
                html += '<li><b>'+data.errors[count]+'</b></li>';
            }
            html += '</div>';
          }

          if (data.success) {
            Swal.fire({
              type: 'success',
              icon: 'success',
              title: 'Berhasil',
              text: 'Data LT 3 berhasil ditambah'
            }).then(function() {
              location.reload();
            });
            $('#formModalsss').modal('hide');
            // html = '<div class="alert alert-success">'+data.success+'</div>';
            $('#sample_formsss')[0].reset();
          }
          $('#form_resultsss').html(html);
        }
      });
    });
  });

  function cancelConfirmation(id) {
    Swal.fire({
      icon: 'warning',
      title: "Batalkan?",
      text: "Apakah anda yakin ingin membatalkan Lead Train 3?",
      type: "warning",
      showCancelButton: !0,
      confirmButtonText: "Yes, Batalkan!",
      cancelButtonText: "Tidak!",
      reverseButtons: !0
    }).then(function (event) {
      if (event.value === true) {
        var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');

        $.ajax({
          type: 'POST',
          url: '/asahan/cancel/'+id+'/lt3',
          data: { _token: CSRF_TOKEN },
          dataType: 'JSON',
          success: function (results) {
            if (results.success === true) {
              Swal.fire({
                toast: false,
                icon: 'success',
                title: "Success",
                text: "Data Deleted",
                showConfirmButton: true,
                // timer: 1500
              }).then(function() {
                location.href = '{{ URL("/asahan/lt2") }}';
              });
            } else {
              Swal.fire("Error!", results.message, "error");
            }
          }
        });
      } else {
        e.dismiss;
      }
    }, function (dismiss) {
      return false;
    });
  }
</script>
@endsection

resources/views/admin/asahan/setting.blade.php
@extends('layouts.master')
@section('title')
Asahan | Setting
@endsection

@section('content')
    <div class="card-box">
        <h3>Ganti Password</h3>
        <button id="pass" class="btn btn-primary">Ganti</button>
    </div>

    @include('partials.modals._cpass')
@endsection